/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        // Stitch "Ethereal Hearth" design tokens
        'on-secondary-container': '#766057',
        'secondary-container': '#fadcd2',
        'on-tertiary': '#ffffff',
        'on-primary-container': '#c19c94',
        'surface-variant': '#e2e3df',
        'on-error': '#ffffff',
        'outline-variant': '#d4c3bf',
        'surface-container-highest': '#e2e3df',
        'on-secondary': '#ffffff',
        secondary: '#6f5a52',
        surface: '#faf9f5',
        'on-secondary-fixed-variant': '#56423b',
        'surface-container-lowest': '#ffffff',
        'inverse-surface': '#2f312e',
        'secondary-fixed': '#fadcd2',
        'on-primary-fixed-variant': '#5c403a',
        'on-tertiary-fixed': '#201a18',
        'on-primary': '#ffffff',
        'tertiary-fixed': '#ece0dc',
        'on-primary-fixed': '#2b1611',
        error: '#ba1a1a',
        'on-tertiary-fixed-variant': '#4c4542',
        'surface-dim': '#dadad6',
        'primary-container': '#4e342e',
        'primary-fixed-dim': '#e5beb5',
        primary: '#361f1a',
        'inverse-on-surface': '#f1f1ed',
        'tertiary-fixed-dim': '#cfc4c0',
        'inverse-primary': '#e5beb5',
        'surface-tint': '#755750',
        'on-background': '#1a1c1a',
        'tertiary-container': '#403936',
        outline: '#827471',
        'surface-container': '#eeeeea',
        'surface-container-high': '#e8e8e4',
        tertiary: '#292421',
        'on-surface-variant': '#504442',
        'on-error-container': '#93000a',
        background: '#faf9f5',
        'on-surface': '#1a1c1a',
        'secondary-fixed-dim': '#ddc1b7',
        'error-container': '#ffdad6',
        'primary-fixed': '#ffdad2',
        'surface-bright': '#faf9f5',
        'on-tertiary-container': '#aca29f',
        'on-secondary-fixed': '#271812',
        'surface-container-low': '#f4f4f0',
      },
      fontFamily: {
        headline: ['"Noto Serif"', 'serif'],
        body: ['Manrope', 'sans-serif'],
        label: ['Manrope', 'sans-serif'],
        sans: ['Manrope', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      boxShadow: {
        card: '0 20px 40px rgba(26, 28, 26, 0.04)',
        'card-hover': '0 30px 60px rgba(26, 28, 26, 0.08)',
        header: '0 20px 40px rgba(26, 28, 26, 0.04)',
        modal: '0 40px 80px rgba(26, 28, 26, 0.08)',
      },
    },
  },
  plugins: [],
}
